title: harperawl.net
email: harperawl@gmail.com
description: >-
  Harper Wicker-Lenseigne's homepage/blog/portfolio/etc.
baseurl: ""
url: "https://harperawl.net"
twitter_username: harperawl
github_username: harperawl

collections:
  pages:
    output: true
    permalink: /:name/

include:
  - _pages